== Download Quellen

Ein Download des Images ist beispielsweise hier
möglich: https://www.raspberrypi.com/software/operating-systems/[Images von raspberrypi.com]

== Aufspielen eines Images

Ohne Imager nutzt man zum Aufspielen eines Images auf die SD Karte  üblicherweise den Linuxbefehl `dd`.
Unter Linux sollte das kein Problem sein :) beim Mac kenne ich mich nicht aus aber da er auf Linux basiert
sollte es da auch irgendwo ein dd geben und unter Windows installiert ihr die gitbash,
die hat ein dd im Bauch. Der Befehl lautet dann:

[source,bash]
----
sudo dd if=/pfad/von/image.img of=/pfad/zur/sdcard bs=4M
----

Die Pfade müsst ihr gemäß Euren verwendeten Pfaden natürlich anpassen.

if:: steht für input Pfad, also der Weg zur Image
of:: steht für output Pfad, also der Weg zur SD Karte (Korrekten Mount Path beachten!).


== SSH aktivieren
Um SSH in einem Image von Anfang an zu aktivieren, muss man **vor dem ersten Booten des Images**
unter dem Folder `/boot/` eine leer Date mit Namen `ssh` anlegen.
Dies kann man über das Kommando `touch` erledigen:

[source,bash]
----
sudo touch /pathToSDCard/boot/ssh
----

Wichtig unter Windows: Darauf achten, dass nicht .txt oder eine andere Endung dran pappt.
Gitbash oder Total Commander sind Euer Freund.

