[reftext="Download Images"]
== Download Quellen

Ein Download des Images ist beispielsweise hier
möglich: https://www.raspberrypi.com/software/operating-systems/[Images von raspberrypi.com]

xref:../../index.adoc#content[Zurück zur Übersicht].

[reftext="Image aufspielen"]
== Aufspielen eines Images

Ohne Imager nutzt man zum Aufspielen eines Images auf die SD Karte  üblicherweise den Linuxbefehl `dd`.
Unter Linux sollte das kein Problem sein :) beim Mac kenne ich mich nicht aus aber da er auf Linux basiert
sollte es da auch irgendwo ein dd geben und unter Windows installiert ihr die gitbash,
die hat ein dd im Bauch. Der Befehl lautet dann:

[source,bash]
----
sudo dd if=/pfad/von/image.img of=/pfad/zur/sdcard bs=4M
----

Die Pfade müsst ihr gemäß Euren verwendeten Pfaden natürlich anpassen.

if:: steht für input Pfad, also der Weg zur Image
of:: steht für output Pfad, also der Weg zur SD Karte (Korrekten Mount Path beachten!).


xref:../../index.adoc#content[Zurück zur Übersicht].

[reftext="SSH aktivieren"]
== SSH aktivieren
Um SSH in einem Image von Anfang an zu aktivieren, muss man **vor dem ersten Booten des Images**
unter dem Folder `/boot/` eine leer Date mit Namen `ssh` anlegen.
Dies kann man über das Kommando `touch` erledigen:

[source,bash]
----
sudo touch /pathToSDCard/boot/ssh
----

Wichtig unter Windows: Darauf achten, dass nicht .txt oder eine andere Endung dran pappt.
Gitbash oder Total Commander sind Euer Freund.


xref:../../index.adoc#content[Zurück zur Übersicht].

== OS Version ermitteln

[source,bash]
----
cat /etc/os-release
----

== Remote Backup vom Pi als Image ziehen

(Quelle: https://pixelfriedhof.com/en/remote-backup-your-raspberry-pi-with-ssh-via-terminal/)

Den aktuellen Zustand des Pi kann man remote per ssh als Image ziehen. Dazu wieder eine Bash öffnen,
unter Windows zum Beispiel die gitbash.

[source,bash]
----
 ssh pi@192.168.20.22 "sudo dd if=/dev/mmcblk0 bs=1M | gzip -" | dd of=~/Desktop/backup20230906.gz
----

IMPORTANT: Der Restore eines Images auf den Pi geht nicht remote. Daher muss der Pi heruntergefahren werden, die
SD Karte entnommen und das Image separat auf die SD Karte übertragen werden.

== Pi Image verkleinern

(Quelle: https://techgeeks.de/raspberry-pi-image-installieren-backup-und-verkleinern/ )

Beim Verkleinern soll keine Information verloren gehen. Es dient nur der Platzverringerung für die Lagerung der Images.
Wenn ein Image auf dem Pi aufgespielt wurde und der Pi läuft, kann das Image jederzeit wieder über die
Einstellung "Expand Filesystem" im folgenden Konfigurationsprogramm `sudo rpi-config` auf das Maximum der SD Karte
vergrößert werden.

Zur Verkleinerung einer abgelegten Imagedatei

[source,bash]
----
 wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
----



[reftext="Nachkonfiguration"]
== Nachkonfiguration auf dem PI

=== Immer zu Beginn

[source,bash]
----
sudo apt update
sudo apt upgrade
----

=== Restart

[source,bash]
----
sudo shutdown -r now
----

=== Halt
[source,bash]
----
sudo shutdown now
----

=== OS Version ermitteln
[source,bash]
----
cat /etc/os-release
----


xref:../../index.adoc#content[Zurück zur Übersicht].

=== APT Lock entfernen

Falls die Remote ssh Verbindung während der Installation abbricht muss man das Lock entfernen und neu aufsetzen.
Es sind genau 2 Lock Dateien zu löschen

[source,bash]
----
sudo rm /var/cache/apt/archives/lock

----

Anschließend muss die Installation neu aufgesetzt werden mit:

[source,bash]
----
sudo dpkg --configure -a
----

=== Allgemeine Konfiguration ändern

Dieses Skript führt die allgemeine Konfiguration auf dem Pi aus. Hier werden sowas wie Sprache, Zeitzone,
Tastaturlayout etc. festgelegt:

[source,bash]
----
/usr/bin/raspi-config
----

xref:../../index.adoc#content[Zurück zur Übersicht].

=== File Transfer

Mit diversen Tools (rcp,rsh,...) lassen sich Dateien vom Pi zu einem anderen Rechner und zurück transportieren. Am einfachsten
funktioniert es mit `scp`. Dieses Werkzeug steht sowohl auf dem Pi als auch in der gitbash unter Windows zur Verfügung.

[source,bash]
----
# Zum Pi kopieren
scp ./meineDatei.pdf pi@raspihostname:/home/pi/meineDatei.pdf
# Vom Pi kopieren, aktuelles Verzeichnis ist schreibbar für mich
scp pi@raspihostname:/home/pi/meineDatei.pdf .
----

xref:../../index.adoc#content[Zurück zur Übersicht].


[reftext="WLAN einrichten"]
== WLAN einrichten

(Quelle: https://www.elektronik-kompendium.de/sites/raspberry-pi/1912221.htm)
Die Eintragungen für das WLAN erfolgen in der Datei wpa_supplicant.conf während der Pi per Netzwerkkabel mit einem PC
verbunden und gestartet ist:

[source,bash]
----
sudo nano /etc/wpa_supplicant/wpa_supplicant.conf
----

Die wpa_supplicant.conf kann beispielsweise für Freifunk Franken so angepasst werden:

[source,bash]
----
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=DE
network={
ssid=”franken.freifunk.net”
key_mgmt=NONE
priority=1
}
----

Anschließend kann die Konfiguration ausprobiert werden:

[source,bash]
----
sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
----

oder über:

[source,bash]
----
ip l
wpa_cli status
----

xref:../../index.adoc#content[Zurück zur Übersicht].

[reftext="Festplatten mounten"]
== USB - Mobile Festplatten einrichten

(Quelle: https://raspberrytips.com/mount-usb-drive-raspberry-pi/)

Für NTFS Platten installieren wir das Paket `ntfs-3g` - meist ist es aber jetzt schon vorhanden.

[source,bash]
----
sudo apt install ntfs-3g
----

Dann schließen wir die Platte an, um mehr Infos zu bekommen und ermitteln die Infos wie folgt:

[source,bash]
----
sudo fdisk -l
----

Jetzt den Filesystemtype und den Device Namen merken.
Beispiele:

`/dev/sda1 ntfs`

Dabei ist `/dev/sda1` der Device Name und `ntfs` der Filesystemtyp.

Wir brauchen noch die `uuid` vom Laufwerk, die finden wir so heraus:

[source,bash]
----
sudo ls -l /dev/disk/by-uuid
----

Die UUID merken wir uns für später. Beispiele für UUIDs: `806203c46203BDC2` oder `37E2-62C3`

Jetzt erstellen wir einen Mount Point z.B. `/mnt/usb` Sollen später mehr Platten angeschlossen werden, hängen wir gleich eine Nummer dran z.B. `/mnt/usb0`

[source,bash]
----
sudo mkdir /mnt/usb
----

Nun wollen wir die Platte noch automatisch mounten lassen. Dazu fügen wir einen Eintrag in die `fstab` ein:

[source,bash]
----
sudo nano /etc/fstab
----

Diese Zeile aufnehmen (Vorher UUID und FS Type anpassen)

`UUID=806203C46203BDC2 /mnt/usb ntfs uid=pi,gid=pi 0 0`

IMPORTANT: !!! Kein Reboot mit fehlerhafter Konfiguration !!!

Jetzt prüfen wir die Konfiguration

[source,bash]
----
sudo mount -a
----

Solange Fehler kommen, bitte  keinen Reboot durchführen. Es kann sonst passieren oder es wird höchstwahrscheinlich passieren,
dass `/` und `/boot` nicht gemountet werden können und das System nicht mehr hochfährt.
Dann geht es für Euch zurück auf Anfang! Oder ihr kennt wen der sich auskennt.
Auf jeden Fall wird es schwierig wenn das automatische mounten kaputt ist.

Im Notfall Eure Zeile wieder entfernen und prüfen ob es jetzt wieder geht.

xref:../../index.adoc#content[Zurück zur Übersicht].

== OS Upgrade (Stretch auf Buster)

(Quelle: https://pimylifeup.com/upgrade-raspbian-stretch-to-raspbian-buster/)

=== OS Version ermitteln

[source,bash]
----
cat /etc/os-release
----

Hier sieht man, welches die nächste Version ist auf die Upgraded wird:
https://en.wikipedia.org/wiki/Raspberry_Pi_OS


=== Pakete aktualisieren

[source,bash]
----
sudo apt update
sudo apt dist-upgrade -y
----

=== Firmware des Pi aktualisieren

Dieser Schritt sollte nur bei Bedarf erfolgen (von 9 auf 10 besteht scheinbar Bedarf).

[source,bash]
----
sudo rpi-update
----

=== Quellen aktualisieren

Jetzt stellen wir die Quellen auf die neuen Repositories der neuen Distribution ein.
Bei uns stellen wir also Stretch auf Buster in den Quellen um.
Später analog halt auf den Namen der neuen Distribution.

[source,bash]
----
sudo nano /etc/apt/sources.list
----

Wir ersetzen in der Zeile **stretch** durch **buster** und speichern und verlassen die Datei.

Jetzt wiederholen wir den Schritt für eine weitere Quellenangabe

[source,bash]
----
sudo nano /etc/apt/sources.list.d/raspi.list
----

Wieder ersetzen wir in der Datei die aktuelle Distribution durch die nachfolgenden Distribution, speichern ab
und schließen den Editor.

=== APT List Changes löschen

Vor dem finalen Upgrade löschen wir noch die ListChanges.

[source,bash]
----
sudo apt-get remove apt-listchanges
----

=== Aktualisieren der neuen Distribution

Jetzt aktualisieren wir die Distribution aus den neuen Quellen. Es ist damit zu rechnen, dass sehr viele
interaktive Abfragen kommen. Also nicht weglaufen sondern dabei bleiben.

[source,bash]
----
sudo apt update
sudo apt dist-upgrade
----

=== Unsupportete Pakete löschen

[source,bash]
----
sudo apt purge timidity lxmusic gnome-disk-utility deluge-gtk evince wicd wicd-gtk clipit usermode gucharmap gnome-system-tools pavucontrol
----

=== Installation aufräumen

[source,bash]
----
sudo apt autoremove -y
----

Wenn erfolgreich dann noch das target autoclean des Paketmanagers aufrufen.

[source,bash]
----
sudo apt autoclean
----

Und zum Abschluss neu starten mit:

[source,bash]
----
sudo reboot
----


