@startuml
salt
{
+3,3 V|(X)|01|---|02|(X)|+5 V
(SDA) GPIO 2|(X)|03|---|04|(X)|+5 V
(SCL) GPIO 3|(X)|05|---|06|(X)|GND
(GPCLK0) GPIO4|(X)|07|---|08|(X)|GPIO 14 (TXD)
...|(X)|09|---|10|(X)|...
...|(X)|11|---|12|(X)|...
...|(X)|13|---|14|(X)|...
...|(X)|15|---|16|(X)|...
...|(X)|17|---|18|(X)|...
...|(X)|19|---|20|(X)|...
...|(X)|21|---|22|(X)|...
...|(X)|23|---|24|(X)|...
...|(X)|25|---|26|(X)|...
...|(X)|27|---|28|(X)|...
...|(X)|29|---|30|(X)|...
...|(X)|31|---|32|(X)|...
...|(X)|33|---|34|(X)|...
...|(X)|35|---|36|(X)|...
...|(X)|37|---|38|(X)|...
...|(X)|39|---|40|(X)|...
}
@enduml