name: Site Creation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Generate Web Site
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '19'
    - name: Commit Generated Website
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/${GITHUB_REPOSITORY}.git
        cd `ls -d */`
        git checkout ${GITHUB_REF_NAME}
        rm -rf docs/*
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        ./mvnw
        git config --global user.email "huluvu424242@gmail.com"
        git config --global user.name "Huluvu424242"
        git remote set-url --push origin https://OWNER:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add docs/*
        git commit -am "neue Doku generiert"
        git push


